export const FETCH_NOTES_BEGIN = 'FETCH_NOTES_BEGIN'
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS'
export const FETCH_NOTES_ERROR = 'FETCH_NOTES_ERROR'

export const POST_NOTES_BEGIN = 'POST_NOTES_BEGIN'
export const POST_NOTES_SUCCESS = 'POST_NOTES_SUCCESS'
export const POST_NOTES_ERROR = 'POST_NOTES_ERROR'
